### ISSUE TITLE
yesbot crashes on Windows operating system

### ISSUE THREAD

**Issue by Anniepoo** [eazar001/yesbot#2] opened 2015-02-05 05:03 UTC
yesbot often crashes, bringing down SWI-Prolog, on startup on Windows.

Observed on settings branch 316354b5c120a9a68b1af605c5a52eb658062831 on win7 64 bit 

Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 7.1.29-5-g0a3d88a)

**Comment by eazar001** [comment] 2015-02-05 06:30
Alright, i'll give this a look after I patch things up on my end. I'll test Linux and Windows.

**Comment by Anniepoo** [comment] 2015-02-06 20:22
<eazar001> i'm not explicitly doing any joins, i know that for sure.
- mescalinum (~mescalinu@gateway/tor-sasl/mescalinum) has joined
  <eazar001> and i'm not trying to do anything _explicitly_ with a detached thread after it is detached
  <eazar001> so i never reference the handle after it is detached
  <eazar001> Anniepoo: one thing you can try to do is git grep detached
  <eazar001> then remove that option in (those 2 occurences, and see if that solves the problem for you)
  <eazar001> alright Anniepoo i'm gonna be out for a few hours, i'll consider doing a refactor so i can maintain desired behavior while also making things safer/stable for windows and possibly other platforms

Well, lets run this to ground first
I can't find the occurances you're talking about, the only one I have is link_shortener

**Comment by eazar001** [comment] 2015-02-06 20:54
Okay, well try removing that option in link_shortener then. That extension will examine each server line to see if it contain a link, so it makes sense that if crashes are happening it would happen even if there are no links to parse. There shouldn't be any other occurrences, I made a mistake with my first statement.

**Comment by eazar001** [comment] 2015-02-06 20:59
Sorry, as a matter of fact, it's probably easier that you just remove `link_shortener/1` and rename `link_shortener_/1` to `link_shortener/1`. That's probably the best way to test it out.

**Comment by Anniepoo** [comment] 2015-02-06 21:05
Did so. No change in behavior.
Tried both removing detached(true) option from link_shortener and doing what you said in your last comment.  I'll be unavailable for a few hours, i need to concentrate on work work.

**Comment by eazar001** [comment] 2015-02-06 21:11
Okay, thanks for testing. I'll try this on a windows virtualbox when I get the chance.

**Comment by eazar001** [comment] 2015-02-07 02:27
Tested for 15 minutes on Windows 7 Ultimate SP1 (32-bit) without a crash. I also attempted 4 other logins without being able to reproduce the issue. I'm not fully convinced that virtualbox however, is an appropriate testing environment. I'll try to test this further on a physical box as soon as I can.

**Comment by eazar001** [comment] 2015-02-07 05:21
I have changed the title of this issue to represent an update: I was able to reproduce this behavior on Linux after some time after merging some of the changes from the `settings` branch onto the `master` branch. Oddly, something within those last few commits from `settings` is causing crashes. This will help to isolate the problem. So far I have not yet experienced this behavior from the `master` or `prolog-irc`, but I'll keep my eyes open.

**Comment by eazar001** [comment] 2015-02-07 06:07
Okay, now i'm tracing the error back as far to commit f6dc2da. Can't go any further than that as of yet. They appear to be segfaults, the origins could reside in code lists.

**Comment by Anniepoo** [comment] 2015-02-07 06:45
Try putting the settings you used on the master branch into one of the crashing cases.  
The problem could be that if you don't explicitly set a setting, it uses the default, and I don't think I used the same defaults you did.

**Comment by eazar001** [comment] 2015-02-07 06:50
After tracing it back even further, I think the problem is on my end. Specifically `link_shortener` seems to be related to the segfaults.

**Comment by eazar001** [comment] 2015-02-07 09:09
I fixed the crashes that _I_ was experiencing. Now I'm just hoping that it will work for your end too. Thanks for bearing with me. Whenever you get the chance, let me know if it works! =]

**Comment by Anniepoo** [comment] 2015-02-07 09:57
OK, I pulled the latest settings branch, and still saw the crash.  I set the extensions setting to [] and it removes the crash.

**Comment by eazar001** [comment] 2015-02-07 22:07
Cannot replicate this issue on a physical Windows 7 Home Premium SP1 (32-bit) box. All extensions were loaded using your new interface too. I'm stumped at the moment.

**Comment by Anniepoo** [comment] 2015-05-25 22:35
Looks like this has reappeared.  crashes if I load chatty and anything else.

Note that I copied link_shortener's code, so maybe that's a clue.

**Comment by eazar001** [comment] 2015-05-26 07:57
I find it curious that in older versions of 7.1.XX on the windows platform, this is not an issue. Is it perhaps a possibility that this could be a SWI bug, rather than a yesbot bug? Of course it's very possible that I'm doing something wrong, it's just that I don't see anything extremely complex about the code, that should warrant such behavior.

**Comment by Anniepoo** [comment] 2015-05-26 18:58
Am I correct that chatty's only failing on my machine? Or on all windows machines? Sorry, I've done too much of this while distracted with other stuff.

**Comment by eazar001** [comment] 2015-05-26 19:01
No. Yesbot fails on all windows machines past a certain _version number_, it's like 7.1.XX or 7.2.X or something. Past that version number, yesbot will fail on windows machines period. Irrespective of chatty.

**Comment by eazar001** [comment] 2015-05-29 08:47
This should be fixed with commit 18f2985e2861b71f18b78a4f3fff9f7d2dc67fbf

**Comment by eazar001** [comment] 2015-05-31 06:08
False positive; will look into tcp code as a potential culprit as you suggested.

**Comment by eazar001** [comment] 2015-06-02 20:14
Fixed via commit aef5727

**Closed as completed by eazar001** 2015-06-02 20:14 UTC
Labels: bug, help wanted
